<?php require_once './templates/header.phtml' ?>

<form method='POST' action='add-new-seguro'>
    <div class="form-group">
        <label for="nombreSeguro">Nombre</label>
        <input type="text" class="form-control" id="nombreSeguro" name='nombreSeguro' placeholder="Nombre del seguro">
    </div>

    <div class="form-group">
        <label for="prestadorId">prestador</label>
        <select class="form-control" name='prestadorId' id='prestadorId'>
            <?php foreach ($prestadores as $prestador) : ?>
                <option value='<?= $prestador->prestadorId ?>'><?= $prestador->nombrePrestador ?></option>
            <?php endforeach ?>
        </select>
    </div>
    <div class="form-group">
        <label for="fechaFinalizacion">Fecha de finalizacion cobertura</label>
        <input type="date" min='0' class="form-control" id="fechaFinalizacion" name='fechaFinalizacion' placeholder="fechaFinalizacion">
    </div>
    <div class="form-group">
        <label for="precio">Precio</label>
        <input type="number" min='0' class="form-control" id="precio" name='precio' placeholder="precio">
    </div>
    <div class="form-group">
        <label for="descripcionSeguro">Descripción del seguro</label>
        <textarea class="form-control" id="descripcionSeguro" name='descripcionSeguro' placeholder="Descripción del seguro"></textarea>

        <button type="submit" class="btn btn-primary">Agregar</button>
        <?php if ($message != null) : ?>
            <div>
                <p><?= $message ?></p>
            </div>
        <?php endif ?>
</form>

<?php require_once './templates/footer.phtml' ?>