<?php require_once './templates/header.phtml' ?>

<form method='POST' action='prestador-edited/<?= $prestador->prestadorId ?>'>
  <div class="form-group">
    <label for="nombrePrestador">Nombre</label>
    <input type="text" class="form-control" id="nombrePrestador" name='nombrePrestador' placeholder="Nombre del prestador" value='<?= $prestador->nombrePrestador ?>'>
  </div>
  <div class="form-group">
    <label for="fechaCreacion">Fecha de fundacion</label>
    <input type="date" class="form-control" id="fechaCreacion" name='fechaCreacion' placeholder="Fecha de creación" value='<?= $prestador->fechaCreacion ?>'>
  </div>
  <div class="form-group">
    <label for="entidad">Entidad</label>
    <input type="text" class="form-control" id="entidad" name='entidad' placeholder="Entidad" value='<?= $prestador->entidad ?>'>
  </div>
  <div class="form-group">
    <label for="opinion">Opinion del prestador</label>
    <textarea class="form-control" id="opinion" name='opinion' placeholder="opinion del prestador"><?= isset($opiniones[0]->opinion) ? $opiniones[0]->opinion : '' ?></textarea>
  </div>
  <div class="form-group">
    <label for="logo">Logo</label>
    <input type="text" class="form-control" id="logo" name='logo' value='<?= $prestador->logo ?>' placeholder="Inserte el link del logo">
  </div>
  <button type="submit" class="btn btn-primary">Editar</button>
</form>

<?php require_once './templates/footer.phtml' ?>