<?php require_once './templates/header.phtml' ?>

<form method='POST' action='seguro-edited/<?= $seguro->seguroId ?>'>
    <div class="form-group">
        <label for="nombreSeguro">Nombre</label>
        <input type="text" class="form-control" id="nombreSeguro" name='nombreSeguro' placeholder="Nombre del seguro" value='<?= $seguro->nombreSeguro ?>'>
    </div>
    <div class="form-group">
        <label for="fechaFinalizacion">Fecha de finalizacion</label>
        <input type="date" class="form-control" id="fechaFinalizacion" name='fechaFinalizacion' placeholder="Fecha de finalizacions" value='<?= $seguro->fechaLanzamiento ?>'>
    </div>
    <div class="form-group">
        <label for="prestadorId">Prestador</label>
        <select class="form-control" name='prestadorId' id='prestadorId'>
            <?php foreach ($prestadores as $prestador) : ?>
                <option <?php if ($seguro->prestadorId == $prestador->prestadorId) : ?>selected<?php endif ?> value='<?= $prestador->prestadorId ?>'><?= $prestador->nombrePrestador ?></option>
            <?php endforeach ?>
        </select>
    </div>
    <div class="form-group">
        <label for="precio">Precio</label>
        <input type="number" min='0' class="form-control" id="precio" name='precio' placeholder="precio" value='<?= $seguro->precio ?>'>
    </div>
    <div class="form-group">
        <label for="descripcionSeguro">Descripción del seguro</label>
        <textarea class="form-control" id="descripcionSeguro" name='descripcionSeguro' placeholder="Descripción del seguro"><?= $seguro->descripcionSeguro ?></textarea>

        <button type="submit" class="btn btn-primary">Editar</button>
</form>

<?php require_once './templates/footer.phtml' ?>